name: Publish to npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: install dependencies
        run: npm ci
      
      - name: lint
        run: npm run lint
      
      - name: run jest tests
        run: npm test
      
      - name: build project
        run: npm run build
      
      - name: publish to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}